version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    tty: true
    env_file:
      - ./.env
    volumes:
      - ./:/docker-web-terminal-frontend
    ports:
      - 9696:9696
